#
# Copyright 2025 the original author or authors.
# <p>
# Licensed under the Moderne Source Available License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# <p>
# https://docs.moderne.io/licensing/moderne-source-available-license
# <p>
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

type: specs.openrewrite.org/v1beta/recipe
name: io.moderne.devcenter.DefaultDevCenter
displayName: Default DevCenter
description: >-
  This is a default DevCenter configuration that can be used as a starting point for your own DevCenter configuration.
  It includes a combination of upgrades, migrations, and security fixes.
  You can customize this configuration to suit your needs.
  For more information on how to customize your DevCenter configuration, see the [DevCenter documentation](https://docs.moderne.io/user-documentation/moderne-platform/getting-started/dev-center/).
recipeList:
  - io.moderne.devcenter.JavaVersionUpgradeStarter
  - io.moderne.devcenter.SpringBootUpgradeStarter
  - io.moderne.devcenter.JUnitUpgradeStarter
  - io.moderne.devcenter.SecurityStarter
---
type: specs.openrewrite.org/v1beta/recipe
name: io.moderne.devcenter.JavaVersionUpgradeStarter
displayName: Starter DevCenter Java version upgrade card
description: >-
  The DevCenter card to upgrade Java versions. The default card uses the open source Java migration recipe.
  You can customize this configuration to include recipes that add to the base Java migration for
  libraries and frameworks that are unique to you.
  For more information on how to customize your DevCenter configuration, see the [DevCenter documentation](https://docs.moderne.io/user-documentation/moderne-platform/getting-started/dev-center/).
tags:
  - DevCenter:fix:org.openrewrite.java.migrate.UpgradeToJava21
recipeList:
  - io.moderne.devcenter.JavaVersionUpgrade:
      targetVersion: 21
---
type: specs.openrewrite.org/v1beta/recipe
name: io.moderne.devcenter.SpringBootUpgradeStarter
displayName: Starter DevCenter Spring Boot version upgrade card
description: >-
  The DevCenter card to upgrade Spring Boot versions. The default card uses the open source Spring Boot migration recipe.
  You can customize this configuration to include recipes that add to the base Spring Boot migration for
  libraries and frameworks that are unique to you.
  For more information on how to customize your DevCenter configuration, see the [DevCenter documentation](https://docs.moderne.io/user-documentation/moderne-platform/getting-started/dev-center/).
tags:
  - DevCenter:fix:io.moderne.java.spring.boot3.UpgradeSpringBoot_3_4
recipeList:
  - io.moderne.devcenter.LibraryUpgrade:
      cardName: Move to Spring Boot 3.4.1
      groupId: org.springframework.boot
      artifactId: '*'
      version: 3.4.1
---
type: specs.openrewrite.org/v1beta/recipe
name: io.moderne.devcenter.JUnitUpgradeStarter
displayName: Starter DevCenter JUnit upgrade card
description: >-
  The DevCenter card to upgrade JUnit. The default card uses the open source JUnit migration recipe.
  You can customize this configuration to include recipes that add to the base JUnit migration for
  customizations that are unique to you.
  For more information on how to customize your DevCenter configuration, see the [DevCenter documentation](https://docs.moderne.io/user-documentation/moderne-platform/getting-started/dev-center/).
tags:
  - DevCenter:fix:org.openrewrite.java.testing.junit5.JUnit4to5Migration
recipeList:
  - io.moderne.devcenter.JUnitUpgrade
---
type: specs.openrewrite.org/v1beta/recipe
name: io.moderne.devcenter.SecurityStarter
displayName: Starter DevCenter security card
description: >-
  This recipe is a starter card to reveal common OWASP Top 10 issues in your source code.
  You can customize this configuration to suit your needs.
  For more information on how to customize your DevCenter configuration, see the [DevCenter documentation](https://docs.moderne.io/user-documentation/moderne-platform/getting-started/dev-center/).
tags:
  # This tag is used by ReportAsSecurityIssues to identify sibling recipes that make up the
  # dimensions of the security DevCenter card.
  - DevCenter:security
recipeList:
  - org.openrewrite.java.security.OwaspA01
  - org.openrewrite.java.security.OwaspA02
  - org.openrewrite.java.security.OwaspA03
  - org.openrewrite.java.security.OwaspA05
  - org.openrewrite.java.security.OwaspA06
  - org.openrewrite.java.security.OwaspA08
  - org.openrewrite.java.security.RegularExpressionDenialOfService
  - org.openrewrite.java.security.secrets.FindSecrets
  - org.openrewrite.java.security.ZipSlip
  - org.openrewrite.java.security.SecureTempFileCreation
  # Changes made by recipes above this one in the recipe list are reported as occurrences
  # in the security DevCenter card.
  - io.moderne.devcenter.ReportAsSecurityIssues
